### ISSUE TITLE
Modifier keys do not display correctly in shortcuts modal dialog

### ISSUE THREAD

**Issue by cpcallen** [rachel-fenichel/blockly-keyboard-experimentation#121]
On certain platforms (Windows, notably), the shortcuts modal dialog does not correctly display certain keys, particularly modifiers (shift, control).

**Comment by bmxedd** [comment]
This is a bug specifically on Windows, where the navigator platform string was incorrectly matched. I will have fix out shortly.

**Comment by bmxedd** [comment]
Additionally we should consider whether the shortcut display in 'Ctrl' on 'Control'. I am aware, this depends on the keyboard the user is using. Convention is to use the shortened version, but children will need to be taught this. This might be reliant on some pre teaching that needs to happen.
