### ISSUE TITLE
Don't highlight children of the selected block with the cursor

### ISSUE THREAD

**Issue by rachel-fenichel** [rachel-fenichel/blockly-keyboard-experimentation#28]
One confusing part is that the cursor currently surrounds an entire stack of blocks when it really only has selected the first block. In this image there is a "draw" block with a stack of three blocks inside. The selection is on the first block ("set stroke color to"), but it surrounds all three blocks.
![image](https://github.com/user-attachments/assets/46b34550-73b0-45a8-b451-18d292ba23e5)

This is a bug in the rendering code rather than an intentional decision.

_Originally posted by @rachel-fenichel in https://github.com/google/blockly-keyboard-experimentation/discussions/10#discussioncomment-10076722_

**Comment by BeksOmega** [comment]
I don't think this is ready to be moved to a task. There's some complexity about how some applications (e.g. scratch) handle actions on selected blocks, and whether they affect next children. I'll add some info to the discussion.
