### ISSUE TITLE
Publish a new release to npm

### ISSUE THREAD

**Issue by rachel-fenichel** [rachel-fenichel/blockly-keyboard-experimentation#84]
For use in testing for Code.org, integrated into their environment.

**Comment by samantha-code** [comment]
Code.org tested the non-experiment environment (mainline) and had a few questions. I believe some of these questions/ concerns have been mitigated in the experiment version but I wanted to post the questions here for posterity. 

About Shift+Control+K: 
🐛:Shift+Control+K opens a new tab in Microsoft Edge: If you have the workspace selected, it does put you into keyboard navigation mode on the current tab, but the browser duplicates the tab and puts you into the new duplicated tab. So you have to ctrl-shift-tab to navigate backwards in the tab order to get back. (or ctrl-w to close the duplicated tab)
Is there any concern about the shift-control-k combination being sufficiently accessible enough? It relies upon the user to hold down 3 keys, probably with two hands.

About Default Cursor:  
Why did we pick Default as the Default Cursor? Line is better for sighted folks, is default better for non-sighted folks? How should we give the options? 

About WASD vs TAB: 
Generally seems like issues with conflicting enter targets for Blockly and non-Blockly - I tried to attach a sound block and the Feedback tab suddenly popped open.

When a drop down is down but not selected properly, can a student still use TAB to navigate across the page? Should we freeze until a choice is made? “I need to remember to Blockly-navigate away (WASD) from the block before tabbing over to Run.” 
Does WASD work with alternate input devices? 

About Block stacks: 
Should we have a hotkey to get to the top of the stack? 
The default position for a new block is on top of other blocks which is confusing



Thoughts for broader group discussion: 
Should we norm on a hotkey for other common access points (for us its run continue workspace)

**Comment by cpcallen** [comment]
`v0.0.1` released.

**Comment by rachel-fenichel** [comment]
@samantha-code fyi this is published.
